### ISSUE TITLE
question on the loss

### ISSUE THREAD

**Issue by haochenglouis** [XLearning-SCU/2021-NeurIPS-NCR#2]
https://github.com/XLearning-SCU/2021-NeurIPS-NCR/blob/c0ea996cba4e23cc1f6b069e638463d6c4cb495f/NCR/model.py#L484

Line 484 and Line 486 in model.py. Should it be "margin" instead of "self.margin" since you have applied soft margin.

**Comment by hi-zhenyu** [comment]
Yes, this is a mistake, I have fix it in  [31dd08e](https://github.com/XLearning-SCU/2021-NeurIPS-NCR/commit/31dd08ec114a9c5abca88fb14b4487ffebaed292).

Thanks for your comment.
