### ISSUE TITLE
是否支持多gpu训练

### ISSUE THREAD

**Issue by sillytheif** [XLearning-SCU/2021-NeurIPS-NCR#4]
想请教一下，这个代码支持多gpu一起训嘛

**Comment by hi-zhenyu** [comment]
目前代码并不支持多GPU运行，NCR单张消费级显卡应该就能运行，且时间不会太长，因此未来暂无支持多GPU的计划。

如果确有这方面的需求的话，建议方式是是直接使用[DataParallel](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html#torch.nn.DataParallel)进行单机多GPU运行，但这类实现运行效率不高。如果有DDP相关使用经验的话，更推荐DDP实现。也欢迎支持多GPU的PR。
